# numpy(넘파이)
## numpy(넘파이)
### numpy(넘파이)
- https://numpy.org/

# 라이브러리 import

In [3]:
import numpy as np

In [1]:
# 만약 이렇게 했다면?
## 만약 이렇게 했다면?
import numpy 

In [4]:
np.array([1,2])

array([1, 2])

## ndarray 
### (1) np.array 함수로 생성

In [5]:
x=[1, 2, 3, 4]
type(x)

list

In [8]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [10]:
type(x)   #리스트가 아니라 ndarray

numpy.ndarray

- 2차원 행렬: 2행 3열

In [11]:
y = np.array([[2, 3, 4],
              [1, 2, 5]])
print(y)

[[2 3 4]
 [1 2 5]]


In [12]:
print(type(y))

<class 'numpy.ndarray'>


### (2) np.arange 함수로 생성
- 파이썬의 range함수와 유사

In [18]:
np.arange()  

TypeError: arange() requires stop to be specified.

In [14]:
# 1이상 10미만
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [17]:
# 5부터 100까지 5의 배수를 생성하시오
np.arange(5,101,5)

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

### (3) np.ones, np.zeros로 생성
https://numpy.org/doc/stable/reference/generated/numpy.ones.html

In [20]:
#4행 5열 행렬, 1로 초기화
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
np.ones(( 3,2, 3, 4))

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

In [24]:
#0으로 초기화 (zeros)
np.zeros((3, 4, 5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [25]:
#4행 5열 행렬 3개 X 2
np.zeros((2, 3, 4, 5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

### (4) reshape 함수 활용
 - ndarray의 형태, 차원을 바꾸기 위해 사용
 - 원본의 형태는 바뀌지 않고 그대로 유지됨
 - 행방향 reshape: order='C' (기본값, 생략가능) 
 - 열방향 reshape: order='F' 

In [26]:
x = np.arange(1, 16)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [36]:
x.shape

(15,)

In [37]:
#2차원 3행 5열로 변경
x.reshape(1, 3, 5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]])

In [40]:
x.reshape(5, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [ ]:
x.reshape(1, 5, 3)

In [41]:
# 이렇게 해도 될까?
x.reshape(5,4)

ValueError: cannot reshape array of size 15 into shape (5,4)

In [45]:
x.reshape(-1,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [46]:
# 열방향으로 reshape하려면?
x.reshape(5, 
          3, 
          order='F')

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [47]:
# x의 형태와 차원을 확인하자!
print(x)
print(x.ndim)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
1


In [ ]:
# x의 차원을 실제 변환하려면 어떻게 해야할까?
x=x.reshape(5, 3)

In [ ]:
# x의 형태와 차원을 다시 확인
print(x)
print(x.ndim)