# ndarray 인덱싱과 슬라이싱

In [1]:
import numpy as np

## 인덱싱
 - 파이썬 리스트와 동일한 개념으로 사용

### 1차원 배열 (1d-array, 벡터) 인덱싱

In [2]:
x = np.arange(1,11)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
#x에서 1을 출력하시오
print(x[0])

1


In [7]:
#x에서 5를 출력하시오
print(x[4])

5


### 2차원 배열 (2d-array, 행렬) 인덱싱

In [8]:
# 0에서 9까지 값을 갖는 1차배열 x와 2차 배열 y(2행 5열)를 만드시오.
x = np.arange(10)
y = x.reshape(2, 5)
print(x)
print(y)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [9]:
y[0, : ]

array([0, 1, 2, 3, 4])

In [10]:
y[0]

array([0, 1, 2, 3, 4])

In [12]:
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
# 3을 출력하려면?
y[0,3]

np.int64(3)

In [17]:
# 3,8을 출력하려면?
y[3]

IndexError: index 3 is out of bounds for axis 0 with size 2

- 1d-array는 항상 가로로 표현! 예)[1,2,3,4,5]

In [ ]:
y

In [15]:
#마지막행, 마지막열
y[-1,-1]

np.int64(9)

### 3차원 배열 (3d-array, 텐서) 인덱싱

In [19]:
# 3행 2열 4개
x = np.arange(24).reshape(4,3,2)
print(x)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [20]:
# 두번째 행렬을 indexing
x[1]

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [21]:
# 두번째 행렬, 첫행을 indexing
x[1,0]

array([6, 7])

In [23]:
# 두번째 행렬, 첫행, 마지막 열을 indexing
x[1,0,-1]

# -1 indexing도 가능한지 확인해 볼것!

np.int64(7)

### 슬라이싱
 - 리스트, 문자열 slicing과 유사하게 사용
 - ,를 사용하여 각 차원별로 슬라이싱 가능

### 1차원 배열 슬라이싱

In [24]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [28]:
#index 1부터 6까지 슬라이싱
x[1:7]

array([1, 2, 3, 4, 5, 6])

In [25]:
x[1:2]

array([1])

In [29]:
#index 1부터 끝까지 슬라이싱
x[1: ]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
#처음부터 끝까지 슬라이싱
x[ : ]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 2차원 배열 슬라이싱

In [30]:
x = np.arange(10).reshape(2, 5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [31]:
x[:, 1:4]  

array([[1, 2, 3],
       [6, 7, 8]])

In [33]:
x[0, :2]

array([0, 1])

In [34]:
x[0:1, :2]

array([[0, 1]])

In [35]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [36]:
# (행) 두번째 행
# (열) 두번째 열에서 4번째 열까지

x[1, 1:4]

array([6, 7, 8])

### 3차원 배열 슬라이싱

In [37]:
#3행 9열 X 2개

x = np.arange(54).reshape(2, 3, 9)
print(x)

[[[ 0  1  2  3  4  5  6  7  8]
  [ 9 10 11 12 13 14 15 16 17]
  [18 19 20 21 22 23 24 25 26]]

 [[27 28 29 30 31 32 33 34 35]
  [36 37 38 39 40 41 42 43 44]
  [45 46 47 48 49 50 51 52 53]]]


In [38]:
x[:1, :2, 1:5]

# (순서) :1 - 처음부터 index 0까지  --> 결국 index 0만
# (행)   :2 - 처음부터 index 1까지
# (열)  1:5 - index 1부터 index 4까지

array([[[ 1,  2,  3,  4],
        [10, 11, 12, 13]]])

In [40]:
x[0, :2, 1:5]

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13]])

- 정리!!
  - indexing: 차원을 감소시킴
  - slicing: 차원을 유지함 

### [추가학습]
- 2d-array의 indexing

In [ ]:
y = np.arange(10).reshape(2, 5)
print(y)

In [ ]:
# 7을 indexing하려면?
print(y[1,2])

- [질문] DataFrame상의 같은 위치도 동일하게 indexing 가능할까?

In [ ]:
import pandas as pd
y2=pd.DataFrame(data=y)
y2

In [ ]:
y2.loc[1,2]

In [ ]:
y2.iloc[1,2]