# ndarray 인덱싱과 슬라이싱

In [1]:
import numpy as np

## 인덱싱
 - 파이썬 리스트와 동일한 개념으로 사용

### 1차원 배열 (1d-array, 벡터) 인덱싱

In [2]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
#x에서 0을 출력하시오
x[0]

0

In [4]:
#x에서 5를 출력하시오
x[5]

5

In [5]:
#x에서 5를 100으로 바꾸어 x를 출력하시오
x[5]=100
x

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

### 2차원 배열 (2d-array) 인덱싱

In [6]:
# 0에서 9까지 값을 갖는 1차배열 x와 2차 배열 y(2행 5열)를 만드시오.
x = np.arange(10)
y = x.reshape(2, 5)
print(x)
print(y)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [7]:
y[0]

array([0, 1, 2, 3, 4])

In [8]:
y[1]

array([5, 6, 7, 8, 9])

In [9]:
y[0,0] 

0

In [10]:
y[1,-1] 

9

#### (list와 비교)

In [11]:
### list에서는 3을 출력하기 위해 어떻게 하였는가?
c=[[1, 2], [3, 4], [5, 6]] 
c[1][0]

3

In [12]:
#그럼 2d-array도 [][]으로 indexing 가능할까?
# 해보세요!

y[1][-1] 

9

### 3차원 배열 (3d-array, 텐서) 인덱싱

In [13]:
# 3행 2열 4개
x = np.arange(24).reshape(4, 3, 2)
print(x)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [14]:
# 두번째 행렬을 indexing
x[1]

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [15]:
# 두번째 행렬, 첫행을 indexing
x[1,0]

array([6, 7])

In [16]:
# 두번째 행렬, 첫행, 마지막 열을 indexing
x[1,0,1]

# -1 indexing도 가능한지 확인해 볼것!

7

### 슬라이싱
 - 리스트, 문자열 slicing과 유사하게 사용
 - ,를 사용하여 각 차원별로 슬라이싱 가능

### 1차원 배열 슬라이싱

In [17]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
x[1:7]

array([1, 2, 3, 4, 5, 6])

In [19]:
#index 1부터 끝까지 슬라이싱
x[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
#처음부터 끝까지 슬라이싱
x[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 2차원 배열 슬라이싱

In [21]:
x = np.arange(10).reshape(2, 5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [22]:
x[:, 1:4]    

array([[1, 2, 3],
       [6, 7, 8]])

In [23]:
x[0, :2]

array([0, 1])

In [24]:
# (행) 두번째 행
# (열) 두번째 열에서 4번째 열까지

x[1,1:4]

array([6, 7, 8])

### 3차원 배열 슬라이싱

In [25]:
#3행 9열 X 2개

x = np.arange(54).reshape(2, 3, 9)
print(x)

[[[ 0  1  2  3  4  5  6  7  8]
  [ 9 10 11 12 13 14 15 16 17]
  [18 19 20 21 22 23 24 25 26]]

 [[27 28 29 30 31 32 33 34 35]
  [36 37 38 39 40 41 42 43 44]
  [45 46 47 48 49 50 51 52 53]]]


In [26]:
x[:1, :2, 1:5]

array([[[ 1,  2,  3,  4],
        [10, 11, 12, 13]]])