# Boolean Indexing

- nd-arry에 bool 리스트 (True, False)를 인덱스처럼 전달하여 True인 경우만 필터링

## 짝수인 경우만 필터링

In [1]:
import numpy as np

- [1,100) 범위에서 10개의 정수 랜덤 추출

In [2]:
x = np.random.randint(1, 100, size=10)
print(x)

[69 23 58 25 78 78 97 96 30 37]


- bool 리스트 생성 (True/False) :x==짝수?

In [3]:
even_mask = (x%2==0)
print(even_mask)

[False False  True False  True  True False  True  True False]


- bool 리스트를 인덱스처럼 전달

In [4]:
x[even_mask]    

array([58, 78, 78, 96, 30])

In [5]:
# True인 인덱스만 표시 - x[even_mask] 와 동일!
x[x%2==0]   

array([58, 78, 78, 96, 30])

In [6]:
# x중 30보다 큰것만 필터링하려면?
x[x>30]

array([69, 58, 78, 78, 97, 96, 37])

##  다중조건으로 필터링
 - ndarray 내에서 파이썬 논리 연산지인 and, or, not 키워드는 사용 불가
 - 대신 기호로 대체함
     - & (AND) 
     - | (OR) 
     - ! (NOT) 

In [7]:
x[(x % 2 == 0) & (x < 30)]

array([], dtype=int32)

In [8]:
# 30미만이거나 50 초과인 것만 필터링 해보세요

x[(x < 30)|(x > 50)]

array([69, 23, 58, 25, 78, 78, 97, 96])