# **Feature - 양적변수** 스케일링
- 서로 다른 변수 값의 범위를 일정한 수준으로 맞추는 것
- 1) Standard Scaling (표준화)
- 2) MinMax  Scaling (정규화, Normalization)

## 1) Standard Scaling (표준화)
- 데이터를 평균이 0이고 분산이 1인 값으로 변환하여 표준정규분포가 되도록 함
*   StandardScaler()

In [1]:
import numpy as np
import pandas as pd

- 붓꽃 데이터 셋을 로딩

In [2]:
iris = pd.read_csv('iris.csv')
iris

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2


In [3]:
#feature만 추출
iris_df=iris.drop('target', axis=1)
iris_df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2
...,...,...,...,...
145,6.7,3.0,5.2,2.3
146,6.3,2.5,5.0,1.9
147,6.5,3.0,5.2,2.0
148,6.2,3.4,5.4,2.3


- feature들의 평균 값

In [5]:
iris_df.mean()

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

- feature들의 분산 값

In [6]:
iris_df.var()

sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64

- StandardScaler class import

In [7]:
from sklearn.preprocessing import StandardScaler

- StandardScaler객체 생성

In [8]:
scaler = StandardScaler()

- StandardScaler객체의 fit( ) 과 transform( ) 호출

In [9]:
scaler.fit(iris_df)

StandardScaler()

In [10]:
iris_scaled = scaler.transform(iris_df)
iris_scaled

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

- transform( )시 scale 변환된 데이터 셋이 numpy ndarry type으로 반환되어 이를 DataFrame으로 변환

In [11]:
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris_df.columns)
iris_df_scaled 

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,-0.900681,1.019004,-1.340227,-1.315444
1,-1.143017,-0.131979,-1.340227,-1.315444
2,-1.385353,0.328414,-1.397064,-1.315444
3,-1.506521,0.098217,-1.283389,-1.315444
4,-1.021849,1.249201,-1.340227,-1.315444
...,...,...,...,...
145,1.038005,-0.131979,0.819596,1.448832
146,0.553333,-1.282963,0.705921,0.922303
147,0.795669,-0.131979,0.819596,1.053935
148,0.432165,0.788808,0.933271,1.448832


- feature들의 평균 값

In [12]:
iris_df_scaled.mean()

sepal length (cm)   -4.736952e-16
sepal width (cm)    -7.815970e-16
petal length (cm)   -4.263256e-16
petal width (cm)    -4.736952e-16
dtype: float64

- feature들의 분산 값

In [13]:
iris_df_scaled.var()

sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64

## 2) MinMax  Scaling (정규화)
- 데이터를 0과 1사이의 값으로 변환함 
* MinMaxScaler()

In [14]:
from sklearn.preprocessing import MinMaxScaler

* **MinMaxScaler객체 생성**

In [15]:
scaler = MinMaxScaler()

* **MinMaxScaler 로 데이터 셋 변환. fit() 과 transform() 호출** 

In [16]:
scaler.fit(iris_df)

MinMaxScaler()

In [17]:
iris_scaled = scaler.transform(iris_df)
iris_scaled

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

- feature들의 최소 값

In [20]:
iris_scaled.min(axis=0)

array([0., 0., 0., 0.])

- feature들의 최대 값

In [21]:
iris_scaled.max(axis=0)

array([1., 1., 1., 1.])

## 3) Scaler 이용시 주의사항 
- fit(): 스케일링을 위한 기준정보 설정 (ex. 데이터 세트의 최대값/최소값 설정)
    - train 셋에만 적용
- transform() : 설정된 정보를 바탕으로 데이터 변환(scaling)
    - train 셋 / test셋 모두 적용

- 즉 train셋으로 fit()된 스케일링 기준 정보를 그대로 test셋에 적용!
- 만약 test셋으로 다시 fit()하게 되면 스케일링 기준정보가 서로 달라짐

### [예제]
- train 셋: 0,1,2,...,10
- test 셋: 0,2,..,5

In [22]:
from sklearn.preprocessing import MinMaxScaler

* 주의) Scaler클래스의 fit(), transform()은 2차원 이상 데이터만 가능
    - reshape(-1, 1)로 차원 변경

In [23]:
train_array = np.arange(0, 11)
train_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
test_array =  np.arange(0, 6)
test_array

array([0, 1, 2, 3, 4, 5])

In [25]:
# MinMaxScaler객체 생성
scaler = MinMaxScaler()

- train_array로 fit()하게 되면 train_array 데이터의 최소값이 0, 최대값이 10으로 설정

In [27]:
scaler.fit(train_array)

ValueError: Expected 2D array, got 1D array instead:
array=[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

- 왜 에러가 날까??
- fit()함수는 2d의 X 데이터를 원함!!

In [28]:
# 어떻게 수정해야 2d로 변형될까?
train_array = np.arange(0, 11).reshape(-1,1)
train_array

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [29]:
test_array =  np.arange(0, 6).reshape(-1,1)
test_array

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

- transform() - 1/10 scale로 데이터 변환
    - 10이 1로 변환

In [30]:
train_scaled = scaler.fit(train_array)
train_scaled

MinMaxScaler()

In [31]:
test_scaled = scaler.transform(test_array)
test_scaled

array([[0. ],
       [0.1],
       [0.2],
       [0.3],
       [0.4],
       [0.5]])

- 질문1) 만약 test_darray =[0,1,2,........20]이라면 어떻게 transform될까?
- 질문2) 만약 test_darray =[-5,-4,-3,..0,..,3,4,5]라면 어떻게 transform될까?

- 만약 test셋으로도 fit을 하게되면 어떻게 될까?

In [34]:
# test 셋: fit/trainsform
scaler.fit(test_array)
test_scaled = scaler.transform(test_array) # 5->1로 변환 

In [38]:
# test 셋 확인
print('원본 test_array 데이터:\n', test_array)
print('Scale된 test_array 데이터:\n', test_scaled)

원본 test_array 데이터:
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
Scale된 test_array 데이터:
 [[0. ]
 [0.2]
 [0.4]
 [0.6]
 [0.8]
 [1. ]]


- 학습데이터와 테스트데이터가 동일한 범위값으로 변환되는 심각한 문제 발생!
- 따라서, fit은 train 셋에만 적용해야 함!